### ISSUE TITLE
Terraform: Error launching instance, possible mismatch of Security Group IDs and Names.

### ISSUE THREAD

**Issue by adrianz-kainos** [KainosSoftwareLtd/aws-api-gateway-demo#3]
Error applying plan:

2 error(s) occurred:
- aws_instance.customer_msvc: Error launching instance, possible mismatch of Security Group IDs and Names. See AWS Instance docs here: https://terraform.io/docs/providers/aws/r/instance.html.
  
  AWS Error: Value () for parameter groupId is invalid. The value cannot be empty
- aws_instance.food_msvc: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'microservices' does not exist
  status code: 400, request id: d31e04c3-370e-468e-8e84-4bc9c80e4e59

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by adrianz-kainos** [comment]
This error disappears after running
`terraform destroy`
and
`terraform apply`
again. Need to check why.

**Comment by adrianz-kainos** [comment]
This error disappears after running:
`terraform destroy`
and then again:
`terraform apply`
Need to check why.

**Comment by adrianz-kainos** [comment]
Possible cause: http://stackoverflow.com/a/34586893

**Comment by adrianz-kainos** [comment]
Fixed by switching from

```
security_groups = ["allow_all"]
```

to

```
vpc_security_group_ids = ["${aws_security_group.allow_all.id}"]
```

**Comment by silviarotari** [comment]
#
